import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "@/app/globals.css";

import "./globals.css";
import { Providers } from "@/store/providers";

const inter = Inter({ subsets: ["latin"], variable: "--font-inter" });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html>
      <body className={` ${inter.variable} antialiased`}>
        <Providers> {children}</Providers>
      </body>
    </html>
  );
}
